import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <nav>put here common layout for entire application</nav>
        {children}
        </body>
    </html>
  )
}
